include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/firebase_options.dart"
  errors:
    extraneous_modifier: ignore

linter:
  rules:
    public_member_api_docs: false
