// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Vp9okbDB_CVPsef7U0CtiPrPzUN_ZTs',
    appId: '1:335544571045:web:09e6de694e11e3e20e694c',
    messagingSenderId: '335544571045',
    projectId: 'warranty-tracker-a6492',
    authDomain: 'warranty-tracker-a6492.firebaseapp.com',
    databaseURL: 'https://warranty-tracker-a6492-default-rtdb.firebaseio.com',
    storageBucket: 'warranty-tracker-a6492.appspot.com',
    measurementId: 'G-C0CX1EHLWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8P5RiHEZn7HY6co73iZwB7xo94VrBJVU',
    appId: '1:335544571045:android:95952276f4d86e0a0e694c',
    messagingSenderId: '335544571045',
    projectId: 'warranty-tracker-a6492',
    databaseURL: 'https://warranty-tracker-a6492-default-rtdb.firebaseio.com',
    storageBucket: 'warranty-tracker-a6492.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGrVBTY0phaqM9Ld4oq2Pq1HAr7DNPSUc',
    appId: '1:335544571045:ios:fc214c268fb064230e694c',
    messagingSenderId: '335544571045',
    projectId: 'warranty-tracker-a6492',
    databaseURL: 'https://warranty-tracker-a6492-default-rtdb.firebaseio.com',
    storageBucket: 'warranty-tracker-a6492.appspot.com',
    androidClientId:
        '335544571045-btg9lfgm4vpsid4lhmq4sebpjjbvcmop.apps.googleusercontent.com',
    iosClientId:
        '335544571045-v3kii6cl4tki4i38cee7f4dglcuts7t2.apps.googleusercontent.com',
    iosBundleId: 'com.warranty-watch.underDevelopment',
  );
}
